# Generated by Django 6.1 on 2026-09-21 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentathletelink',
            name='approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='parentathletelink',
            index=models.Index(fields=['parent', 'approved'], name='parent_link_access_idx'),
        ),
        migrations.AddIndex(
            model_name='parentathletelink',
            index=models.Index(fields=['athlete', 'approved'], name='athlete_link_access_idx'),
        ),
        migrations.AddConstraint(
            model_name='parentathletelink',
            constraint=models.UniqueConstraint(fields=('parent', 'athlete'), name='unique_parent_athlete_link'),
        ),
        migrations.AddConstraint(
            model_name='parentathletelink',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('athlete')), _negated=True), name='parent_cannot_link_to_self'),
        ),
    ]
