from typing import Any


def build_mock_feedback(
    measurements: dict[str, Any],
) -> dict[str, Any]:
    """
    Convert demonstration measurements into demonstration
    coaching observations.

    No real computer vision or coaching analysis occurs here.
    """

    return {
        'summary': (
            'This is a demonstration analysis used to test '
            'the NewSchool Gymnastics AI workflow. These '
            'results were not generated by a real '
            'computer-vision model and must not be treated '
            'as technical coaching feedback.'
        ),
        'strengths': [
            (
                'The athlete maintained a controlled body '
                'position through the main phase.'
            ),
            (
                'The movement showed a clear beginning, '
                'middle, and finish.'
            ),
        ],
        'improvements': [
            (
                'Review body alignment during the key '
                'technical position.'
            ),
            (
                'Compare the finish position with an earlier '
                'attempt before making a coaching decision.'
            ),
        ],
        'measurements': measurements,
    }