# Generated by Django 6.1 on 2026-09-02 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PathwayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('vault', 'Vault'), ('bars', 'Uneven Bars'), ('beam', 'Beam'), ('floor', 'Floor')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PathwayLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('minimum_age', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_age', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AthletePathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('developing', 'Developing'), ('on_track', 'On Track'), ('ready', 'Ready for Next Level'), ('hold', 'Hold')], default='developing', max_length=30)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('head_coach_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.OneToOneField(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='hp_pathway', to=settings.AUTH_USER_MODEL)),
                ('managed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hp_pathways', to=settings.AUTH_USER_MODEL)),
                ('current_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_athletes', to='pathway.pathwaylevel')),
                ('target_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_athletes', to='pathway.pathwaylevel')),
            ],
        ),
        migrations.CreateModel(
            name='PathwayRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('skill', 'Skill'), ('cr', 'Composition Requirement'), ('bonus', 'Bonus'), ('dv', 'Difficulty Value'), ('routine', 'Routine Requirement'), ('vault', 'Vault Option'), ('equipment', 'Equipment'), ('competition', 'Competition Requirement'), ('other', 'Other')], default='skill', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('requirement_number', models.PositiveIntegerField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bonus_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='pathway.pathwayevent')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='pathway.pathwaylevel')),
                ('parent_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_requirements', to='pathway.pathwayrequirement')),
            ],
            options={
                'ordering': ['level__order', 'event__order', 'display_order', 'requirement_number', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AthletePathwayRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('learning', 'Learning'), ('developing', 'Developing'), ('ready', 'Competition Ready'), ('mastered', 'Mastered'), ('not_required', 'Not Required')], default='not_started', max_length=30)),
                ('coach_note', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('custom_title', models.CharField(blank=True, max_length=200)),
                ('is_hidden_from_parent', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_requirements', to='pathway.athletepathway')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pathway_requirements', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_statuses', to='pathway.pathwayrequirement')),
            ],
            options={
                'ordering': ['requirement__event__order', 'requirement__display_order'],
                'constraints': [models.UniqueConstraint(fields=('athlete_pathway', 'requirement'), name='unique_athlete_pathway_requirement')],
            },
        ),
    ]
