# Generated by Django 6.1 on 2026-09-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletepathwayrequirement',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('developing', 'Developing'), ('achieved', 'Achieved'), ('competition_ready', 'Competition Ready')], default='not_started', max_length=30),
        ),
    ]
