# Generated by Django 6.1 on 2026-09-03 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway', '0002_alter_athletepathwayrequirement_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('vault', 'Vault'), ('bars', 'Uneven Bars'), ('beam', 'Beam'), ('floor', 'Floor')], max_length=20)),
                ('name', models.CharField(default='Competition Routine', max_length=120)),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='hp_routines', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hp_routines', to=settings.AUTH_USER_MODEL)),
                ('pathway_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athlete_routines', to='pathway.pathwaylevel')),
            ],
            options={
                'ordering': ['athlete__first_name', 'athlete__last_name', 'event', '-is_current', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AthleteRoutineElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=150)),
                ('difficulty', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E+', 'E+')], max_length=5)),
                ('difficulty_value', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('element_type', models.CharField(choices=[('acro', 'Acro'), ('dance', 'Dance'), ('other', 'Other')], default='other', max_length=20)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_dismount', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='pathway.athleteroutine')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AthleteRoutineRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_met', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_uses', to='pathway.pathwayrequirement')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_requirements', to='pathway.athleteroutine')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('routine', 'requirement'), name='unique_routine_requirement')],
            },
        ),
    ]
