# Generated by Django 6.1 on 2026-09-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathway', '0003_athleteroutine_athleteroutineelement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleteroutineelement',
            name='vault_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
