# Generated by Django 6.0.3 on 2026-07-25 14:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('practice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('planned_intensity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('competition', 'Competition Simulation')], default='moderate', max_length=20)),
                ('primary_focus', models.CharField(blank=True, max_length=200)),
                ('coach_objectives', models.TextField(blank=True)),
                ('general_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assistant_coaches', models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['coach', 'head_coach']}, related_name='assisted_practice_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_practice_plans', to=settings.AUTH_USER_MODEL)),
                ('lead_coach', models.ForeignKey(limit_choices_to={'role__in': ['coach', 'head_coach']}, on_delete=django.db.models.deletion.PROTECT, related_name='led_practice_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-practice_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PracticeRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('event', models.CharField(choices=[('vault', 'Vault'), ('bars', 'Bars'), ('beam', 'Beam'), ('floor', 'Floor'), ('trampoline', 'Trampoline'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('conditioning', 'Conditioning'), ('dance', 'Dance'), ('warmup', 'Warm-up'), ('testing', 'Testing'), ('recovery', 'Recovery'), ('other', 'Other')], max_length=30)),
                ('order', models.PositiveIntegerField(default=1)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('objective', models.CharField(blank=True, max_length=250)),
                ('coach_notes', models.TextField(blank=True)),
                ('is_testing_rotation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_coach', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['coach', 'head_coach']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_practice_rotations', to=settings.AUTH_USER_MODEL)),
                ('practice_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='practice_planner.practiceplan')),
            ],
            options={
                'ordering': ['practice_plan', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PracticeStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('station_type', models.CharField(choices=[('drill', 'Drill'), ('skill', 'Skill'), ('exercise', 'Exercise'), ('test', 'Testing Exercise'), ('routine', 'Routine'), ('conditioning', 'Conditioning'), ('recovery', 'Recovery'), ('other', 'Other')], default='drill', max_length=30)),
                ('order', models.PositiveIntegerField(default=1)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('sets', models.PositiveIntegerField(blank=True, null=True)),
                ('repetitions', models.PositiveIntegerField(blank=True, null=True)),
                ('target_attempts', models.PositiveIntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('coaching_cues', models.TextField(blank=True)),
                ('equipment', models.CharField(blank=True, max_length=250)),
                ('success_criteria', models.TextField(blank=True)),
                ('reference_video_url', models.URLField(blank=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='practice_planner.practicerotation')),
            ],
            options={
                'ordering': ['rotation', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athletes', models.ManyToManyField(blank=True, limit_choices_to={'role': 'athlete'}, related_name='practice_groups', to=settings.AUTH_USER_MODEL)),
                ('coaches', models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['coach', 'head_coach']}, related_name='practice_training_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='practiceplan',
            name='training_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='practice_plans', to='practice_planner.traininggroup'),
        ),
        migrations.CreateModel(
            name='PracticeAthleteAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload', models.CharField(choices=[('full', 'Full Training'), ('modified', 'Modified Training'), ('recovery', 'Recovery Program'), ('observe', 'Observe Only'), ('excused', 'Excused')], default='full', max_length=20)),
                ('is_expected', models.BooleanField(default=True)),
                ('restrictions', models.TextField(blank=True)),
                ('individual_focus', models.TextField(blank=True)),
                ('coach_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='practice_assignments', to=settings.AUTH_USER_MODEL)),
                ('practice_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_assignments', to='practice_planner.practiceplan')),
            ],
            options={
                'ordering': ['athlete__first_name', 'athlete__last_name', 'athlete__username'],
                'constraints': [models.UniqueConstraint(fields=('practice_plan', 'athlete'), name='unique_athlete_assignment_per_practice')],
            },
        ),
        migrations.AddConstraint(
            model_name='practicerotation',
            constraint=models.UniqueConstraint(fields=('practice_plan', 'order'), name='unique_rotation_order_per_practice'),
        ),
        migrations.AddConstraint(
            model_name='practicestation',
            constraint=models.UniqueConstraint(fields=('rotation', 'order'), name='unique_station_order_per_rotation'),
        ),
    ]
