# Generated by Django 6.0.3 on 2026-07-27 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_testing', '0004_testingsession_practice_plan_testingsession_status_and_more'),
        ('practice_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicerotation',
            name='testing_session',
            field=models.ForeignKey(blank=True, help_text='Select the existing Performance Testing session used during this rotation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_rotations', to='performance_testing.testingsession'),
        ),
    ]
