# Generated by Django 6.0.3 on 2026-07-30 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_planner', '0002_practicerotation_testing_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('general', 'General Practice'), ('event_focus', 'Event Focus'), ('competition', 'Competition Preparation'), ('recovery', 'Recovery Practice'), ('conditioning', 'Conditioning'), ('testing', 'Testing'), ('camp', 'Camp'), ('other', 'Other')], default='general', max_length=30)),
                ('level', models.CharField(blank=True, help_text='Examples: Aspire 1, HP Novice, Level 7.', max_length=100)),
                ('season_phase', models.CharField(blank=True, help_text='Examples: Preseason, Competition Season, Recovery.', max_length=100)),
                ('planned_intensity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('competition', 'Competition Simulation')], default='moderate', max_length=20)),
                ('primary_focus', models.CharField(blank=True, max_length=200)),
                ('coach_objectives', models.TextField(blank=True)),
                ('general_notes', models.TextField(blank=True)),
                ('default_duration_minutes', models.PositiveIntegerField(default=180, help_text='The normal total duration of practices created from this template.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_shared', models.BooleanField(default=False, help_text='Shared templates can be viewed and used by other coaches.')),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_practice_templates', to=settings.AUTH_USER_MODEL)),
                ('source_practice', models.ForeignKey(blank=True, help_text='The original practice used to create this template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_templates', to='practice_planner.practiceplan')),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PracticeTemplateRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('event', models.CharField(choices=[('vault', 'Vault'), ('bars', 'Bars'), ('beam', 'Beam'), ('floor', 'Floor'), ('trampoline', 'Trampoline'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('conditioning', 'Conditioning'), ('dance', 'Dance'), ('warmup', 'Warm-up'), ('testing', 'Testing'), ('recovery', 'Recovery'), ('other', 'Other')], max_length=30)),
                ('order', models.PositiveIntegerField(default=1)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('objective', models.CharField(blank=True, max_length=250)),
                ('coach_notes', models.TextField(blank=True)),
                ('is_optional', models.BooleanField(default=False, help_text='Optional rotations can be skipped when creating a shorter practice.')),
                ('include_testing', models.BooleanField(default=False, help_text='Marks this rotation as a testing block. A testing session will be selected when the new practice is created.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='practice_planner.practicetemplate')),
            ],
            options={
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PracticeTemplateStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('station_type', models.CharField(choices=[('drill', 'Drill'), ('skill', 'Skill'), ('exercise', 'Exercise'), ('test', 'Testing Exercise'), ('routine', 'Routine'), ('conditioning', 'Conditioning'), ('recovery', 'Recovery'), ('other', 'Other')], default='drill', max_length=30)),
                ('order', models.PositiveIntegerField(default=1)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('sets', models.PositiveIntegerField(blank=True, null=True)),
                ('repetitions', models.PositiveIntegerField(blank=True, null=True)),
                ('target_attempts', models.PositiveIntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('coaching_cues', models.TextField(blank=True)),
                ('equipment', models.CharField(blank=True, max_length=250)),
                ('success_criteria', models.TextField(blank=True)),
                ('reference_video_url', models.URLField(blank=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='practice_planner.practicetemplaterotation')),
            ],
            options={
                'ordering': ['template_rotation', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='practicetemplate',
            constraint=models.UniqueConstraint(fields=('created_by', 'name'), name='unique_practice_template_name_per_coach'),
        ),
        migrations.AddConstraint(
            model_name='practicetemplaterotation',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='unique_rotation_order_per_practice_template'),
        ),
        migrations.AddConstraint(
            model_name='practicetemplatestation',
            constraint=models.UniqueConstraint(fields=('template_rotation', 'order'), name='unique_station_order_per_template_rotation'),
        ),
    ]
