# Generated by Django 6.1 on 2026-09-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Platform Admin'), ('director', 'Gym Director'), ('head_coach', 'Head Coach'), ('coach', 'Coach'), ('athlete', 'Athlete'), ('parent', 'Parent')], max_length=20),
        ),
    ]
