# Generated by Django 6.1 on 2026-09-08 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_coachnote_teamevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coachathleteassignment',
            constraint=models.UniqueConstraint(fields=('coach', 'athlete'), name='unique_coach_athlete_assignment'),
        ),
    ]
