# Generated by Django 6.1 on 2026-09-09 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_coachathleteassignment_unique_coach_athlete_assignment'),
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coachathleteassignment',
            name='unique_coach_athlete_assignment',
        ),
        migrations.AddField(
            model_name='teamevent',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_events', to='gyms.gym'),
        ),
    ]
