# Generated by Django 6.0.3 on 2026-03-20 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date', models.DateField()),
                ('energy', models.PositiveSmallIntegerField(default=3)),
                ('soreness', models.PositiveSmallIntegerField(default=3)),
                ('stress', models.PositiveSmallIntegerField(default=3)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('ate_well', models.BooleanField(default=False)),
                ('hydrated', models.BooleanField(default=False)),
                ('soreness_area', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_surveys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-survey_date', '-created_at'],
                'unique_together': {('athlete', 'survey_date')},
            },
        ),
    ]
