# Generated by Django 6.0.3 on 2026-03-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysurvey',
            name='energy',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Very Low'), (2, '2 - Low'), (3, '3 - Okay'), (4, '4 - Good'), (5, '5 - Great')], default=3),
        ),
        migrations.AlterField(
            model_name='dailysurvey',
            name='soreness',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Very Low'), (2, '2 - Low'), (3, '3 - Okay'), (4, '4 - Good'), (5, '5 - Great')], default=3),
        ),
        migrations.AlterField(
            model_name='dailysurvey',
            name='stress',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Very Low'), (2, '2 - Low'), (3, '3 - Okay'), (4, '4 - Good'), (5, '5 - Great')], default=3),
        ),
    ]
