# Generated by Django 6.0.3 on 2026-08-03 21:12

import django.db.models.deletion
import video_library.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practice_planner', '0003_practicetemplate_practicetemplaterotation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('video_file', models.FileField(upload_to=video_library.models.video_upload_path)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=video_library.models.thumbnail_upload_path)),
                ('event', models.CharField(choices=[('vault', 'Vault'), ('bars', 'Bars'), ('beam', 'Beam'), ('floor', 'Floor'), ('trampoline', 'Trampoline'), ('strength', 'Strength'), ('conditioning', 'Conditioning'), ('flexibility', 'Flexibility'), ('dance', 'Dance'), ('other', 'Other')], default='other', max_length=30)),
                ('skill_name', models.CharField(blank=True, help_text='Examples: Jager, Pak salto, beam series, Yurchenko layout.', max_length=150)),
                ('video_type', models.CharField(choices=[('practice', 'Practice'), ('competition', 'Competition'), ('testing', 'Performance Testing'), ('drill', 'Drill'), ('routine', 'Routine'), ('progress', 'Progress Video'), ('other', 'Other')], default='practice', max_length=30)),
                ('recorded_at', models.DateTimeField(blank=True, help_text='When the video was recorded. If unknown, the upload time will still be saved.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Separate tags with commas. Example: release, competition routine, personal best', max_length=300)),
                ('visibility', models.CharField(choices=[('coaches', 'Coaches Only'), ('athlete', 'Coaches and Athlete'), ('parents', 'Coaches, Athlete and Parents'), ('private', 'Uploader Only')], default='coaches', max_length=20)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('ready', 'Ready'), ('failed', 'Upload Failed'), ('archived', 'Archived')], default='ready', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('ai_status', models.CharField(choices=[('not_requested', 'Not Requested'), ('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='not_requested', max_length=30)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_results', models.JSONField(blank=True, default=dict, help_text='Structured AI results such as detected skills, body angles, deductions, and confidence scores.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('practice_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='practice_planner.practiceplan')),
                ('primary_athlete', models.ForeignKey(blank=True, limit_choices_to={'role': 'athlete'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_gymnastics_videos', to=settings.AUTH_USER_MODEL)),
                ('tagged_athletes', models.ManyToManyField(blank=True, help_text='Use this when more than one athlete appears in the video.', limit_choices_to={'role': 'athlete'}, related_name='tagged_gymnastics_videos', to=settings.AUTH_USER_MODEL)),
                ('training_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='practice_planner.traininggroup')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_gymnastics_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('coach_feedback', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_coach', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['coach', 'head_coach']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_video_reviews', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_video_reviews', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='video_library.video')),
            ],
            options={
                'ordering': ['status', '-requested_at'],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['event', 'skill_name'], name='video_event_skill_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status', 'uploaded_at'], name='video_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['ai_status'], name='video_ai_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='videoreview',
            constraint=models.UniqueConstraint(fields=('video', 'assigned_coach'), name='unique_video_review_per_coach'),
        ),
    ]
