# Generated by Django 6.0.3 on 2026-08-06 21:20

import django.db.models.deletion
import video_library.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('preparing', 'Preparing Video'), ('processing', 'Processing Frames'), ('generating_results', 'Generating Results'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=30)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, help_text='Processing progress from 0 to 100.')),
                ('current_step', models.CharField(blank=True, help_text='Short processing message shown to the coach.', max_length=200)),
                ('analysis_source', models.CharField(choices=[('mock', 'Mock Analysis'), ('pose', 'Pose Analysis'), ('multimodal', 'Multimodal Analysis'), ('hybrid', 'Hybrid Analysis')], default='mock', max_length=30)),
                ('analysis_version', models.CharField(default='0.1.0', help_text='Version of the analysis pipeline used.', max_length=50)),
                ('requested_skill', models.CharField(blank=True, help_text='Skill supplied by the coach before analysis.', max_length=150)),
                ('detected_skill', models.CharField(blank=True, max_length=150)),
                ('skill_confidence', models.DecimalField(blank=True, decimal_places=4, help_text='Confidence between 0.0000 and 1.0000.', max_digits=5, null=True)),
                ('summary', models.TextField(blank=True)),
                ('strengths', models.JSONField(blank=True, default=list, help_text='List of positive technical observations.')),
                ('improvements', models.JSONField(blank=True, default=list, help_text='List of recommended technical improvements.')),
                ('measurements', models.JSONField(blank=True, default=dict, help_text='Structured angles, timing, distances, and movement measurements.')),
                ('raw_results', models.JSONField(blank=True, default=dict, help_text='Complete structured output from the analysis pipeline.')),
                ('annotated_video', models.FileField(blank=True, null=True, upload_to=video_library.models.analysis_video_upload_path)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_seconds', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Coach Review'), ('approved', 'Approved'), ('partial', 'Partially Correct'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('coach_review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_video_analyses', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_video_analyses', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='video_library.video')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoAnalysisMoment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp_seconds', models.DecimalField(decimal_places=3, max_digits=10)),
                ('end_timestamp_seconds', models.DecimalField(blank=True, decimal_places=3, help_text='Optional end timestamp for a phase or range.', max_digits=10, null=True)),
                ('moment_type', models.CharField(choices=[('start', 'Start'), ('approach', 'Approach'), ('takeoff', 'Takeoff'), ('hand_support', 'Hand Support'), ('release', 'Release'), ('flight', 'Flight'), ('catch', 'Catch'), ('landing', 'Landing'), ('finish', 'Finish'), ('observation', 'Observation'), ('other', 'Other')], default='observation', max_length=30)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('positive', 'Positive'), ('warning', 'Needs Attention'), ('critical', 'Significant Concern')], default='info', max_length=20)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('measurements', models.JSONField(blank=True, default=dict)),
                ('frame_image', models.ImageField(blank=True, null=True, upload_to=video_library.models.analysis_frame_upload_path)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='video_library.videoanalysis')),
            ],
            options={
                'ordering': ['timestamp_seconds', 'display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VideoAnalysisFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('correct', 'Correct'), ('partial', 'Partially Correct'), ('incorrect', 'Incorrect')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='video_library.videoanalysis')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_analysis_feedback', to=settings.AUTH_USER_MODEL)),
                ('moment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='video_library.videoanalysismoment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='videoanalysis',
            index=models.Index(fields=['status', 'created_at'], name='analysis_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='videoanalysis',
            index=models.Index(fields=['video', 'status'], name='analysis_video_status_idx'),
        ),
        migrations.AddIndex(
            model_name='videoanalysis',
            index=models.Index(fields=['review_status'], name='analysis_review_idx'),
        ),
        migrations.AddIndex(
            model_name='videoanalysismoment',
            index=models.Index(fields=['analysis', 'timestamp_seconds'], name='analysis_moment_time_idx'),
        ),
        migrations.AddIndex(
            model_name='videoanalysismoment',
            index=models.Index(fields=['moment_type'], name='analysis_moment_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='videoanalysisfeedback',
            constraint=models.UniqueConstraint(fields=('analysis', 'moment', 'coach'), name='unique_analysis_moment_feedback_per_coach'),
        ),
    ]
