# Generated by Django 6.0.3 on 2026-08-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_library', '0002_videoanalysis_videoanalysismoment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='frame_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_fps',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
