# Generated by Django 6.0.3 on 2026-08-07 22:11

import video_library.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_library', '0003_video_frame_count_video_video_fps_video_video_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysismoment',
            name='annotated_frame_image',
            field=models.ImageField(blank=True, null=True, upload_to=video_library.models.analysis_frame_upload_path),
        ),
    ]
