# Generated by Django 6.0.3 on 2026-08-11 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_library', '0004_videoanalysismoment_annotated_frame_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechniqueProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=120, unique=True)),
                ('strictness', models.CharField(choices=[('developmental', 'Developmental'), ('standard', 'Standard'), ('high_performance', 'High Performance')], default='standard', max_length=30)),
                ('straight_legs', models.BooleanField(default=True)),
                ('body_line', models.BooleanField(default=True)),
                ('shoulder_position', models.BooleanField(default=True)),
                ('straight_arms', models.BooleanField(default=True)),
                ('landing_control', models.BooleanField(default=False)),
                ('takeoff_position', models.BooleanField(default=False)),
                ('tuck_position', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_technique_profiles', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_technique_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['skill_name'],
            },
        ),
    ]
