# Generated by Django 6.0.3 on 2026-08-20 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_library', '0005_techniqueprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='techniqueprofile',
            name='is_coaching_example',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techniqueprofile',
            name='is_personal_best',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techniqueprofile',
            name='is_reference_attempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='techniqueprofile',
            name='reference_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='techniqueprofile',
            name='reference_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_reference_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
