# Generated by Django 6.0.3 on 2026-08-26 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_planner', '0003_practicetemplate_practicetemplaterotation_and_more'),
        ('video_library', '0006_techniqueprofile_is_coaching_example_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techniqueprofile',
            name='is_coaching_example',
        ),
        migrations.RemoveField(
            model_name='techniqueprofile',
            name='is_personal_best',
        ),
        migrations.RemoveField(
            model_name='techniqueprofile',
            name='is_reference_attempt',
        ),
        migrations.RemoveField(
            model_name='techniqueprofile',
            name='reference_marked_at',
        ),
        migrations.RemoveField(
            model_name='techniqueprofile',
            name='reference_marked_by',
        ),
        migrations.RemoveField(
            model_name='video',
            name='frame_count',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_fps',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_height',
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_width',
        ),
        migrations.RemoveField(
            model_name='videoanalysismoment',
            name='annotated_frame_image',
        ),
        migrations.AddField(
            model_name='video',
            name='is_coaching_example',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='is_personal_best',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='is_reference_attempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='reference_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='reference_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_reference_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='ai_results',
            field=models.JSONField(blank=True, default=dict, help_text='Structured AI results such as detected skills, body angles, deductions and confidence scores.'),
        ),
        migrations.AlterField(
            model_name='video',
            name='recorded_at',
            field=models.DateTimeField(blank=True, help_text='When the video was recorded.', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='skill_name',
            field=models.CharField(blank=True, help_text='Examples: Handstand, Jager, Pak salto, beam series.', max_length=150),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.CharField(blank=True, help_text='Separate tags with commas.', max_length=300),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='analysis_version',
            field=models.CharField(default='0.1.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='current_step',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='improvements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='measurements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='raw_results',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='requested_skill',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='skill_confidence',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='videoanalysis',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='videoanalysismoment',
            name='end_timestamp_seconds',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['primary_athlete', 'skill_name', 'is_reference_attempt'], name='video_reference_idx'),
        ),
    ]
