# Generated by Django 6.1 on 2026-09-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_library', '0008_skillgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Converting to MP4'), ('ready', 'Ready'), ('failed', 'Upload Failed'), ('archived', 'Archived')], default='ready', max_length=20),
        ),
    ]
