# Generated by Django 6.0.3 on 2026-07-09 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_attendancerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event', models.CharField(choices=[('vault', 'Vault'), ('bars', 'Bars'), ('beam', 'Beam'), ('floor', 'Floor'), ('strength', 'Strength'), ('flexibility', 'Flexibility')], max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['event', 'name'],
                'unique_together': {('name', 'event')},
            },
        ),
        migrations.CreateModel(
            name='AthleteSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('consistent', 'Consistent'), ('competition_ready', 'Competition Ready'), ('mastered', 'Mastered')], default='not_started', max_length=30)),
                ('started_date', models.DateField(blank=True, null=True)),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_skills', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills_updated', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_progress', to='athletes.skill')),
            ],
            options={
                'ordering': ['skill__event', 'skill__name'],
                'unique_together': {('athlete', 'skill')},
            },
        ),
    ]
