# Generated by Django 6.0.3 on 2026-07-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0005_athletevideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athletevideo',
            options={'ordering': ['-practice_date', '-uploaded_at']},
        ),
        migrations.AddField(
            model_name='athletevideo',
            name='event',
            field=models.CharField(choices=[('vault', 'Vault'), ('bars', 'Bars'), ('beam', 'Beam'), ('floor', 'Floor'), ('strength', 'Strength'), ('flexibility', 'Flexibility'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='athletevideo',
            name='practice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
