# Generated by Django 6.0.3 on 2026-07-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_alter_athletevideo_options_athletevideo_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletevideo',
            name='attempt_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='athletevideo',
            name='coach_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='athletevideo',
            name='review_status',
            field=models.CharField(choices=[('not_reviewed', 'Not Reviewed'), ('reviewed', 'Reviewed'), ('needs_follow_up', 'Needs Follow-Up'), ('highlight', 'Highlight')], default='not_reviewed', max_length=30),
        ),
        migrations.AddField(
            model_name='athletevideo',
            name='technical_focus',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
