# Generated by Django 6.1 on 2026-09-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0007_athletevideo_attempt_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athletevideo',
            options={'ordering': ['-practice_date', '-attempt_number', '-uploaded_at']},
        ),
    ]
