# Generated by Django 6.0.3 on 2026-07-17 20:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('points', 'Points'), ('reps', 'Repetitions'), ('seconds', 'Seconds'), ('minutes', 'Minutes'), ('distance', 'Distance'), ('level', 'Level'), ('text', 'Text Result'), ('pass_fail', 'Pass / Fail')], default='points', max_length=20)),
                ('higher_is_better', models.BooleanField(default=True, help_text='Select this when a higher result is better. Turn it off for timed events where a lower time is better.')),
                ('guidelines', models.TextField(blank=True, help_text='Explain how this exercise is performed and scored.')),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TestingScoringRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Example: 10 L leg lifts', max_length=150)),
                ('comparison', models.CharField(choices=[('gte', 'Greater than or equal to'), ('lte', 'Less than or equal to'), ('between', 'Between'), ('exact', 'Exactly')], default='gte', max_length=20)),
                ('minimum_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('maximum_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('points', models.DecimalField(decimal_places=2, max_digits=7)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_rules', to='performance_testing.testingexercise')),
            ],
            options={
                'ordering': ['exercise__display_order', 'display_order', 'points'],
            },
        ),
        migrations.CreateModel(
            name='TestingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('testing_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('allow_athlete_entry', models.BooleanField(default=False, help_text='Allow athletes to submit their own results for coach review.')),
                ('published_to_athletes', models.BooleanField(default=False)),
                ('published_to_parents', models.BooleanField(default=False)),
                ('show_rankings_to_athletes', models.BooleanField(default=True)),
                ('show_rankings_to_parents', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_testing_sessions', to=settings.AUTH_USER_MODEL)),
                ('exercises', models.ManyToManyField(related_name='testing_sessions', to='performance_testing.testingexercise')),
            ],
            options={
                'ordering': ['-testing_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AthleteTestingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Coach Verification'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('coach_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_testing_results', to=settings.AUTH_USER_MODEL)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_performance_testing_results', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_performance_testing_results', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_results', to='performance_testing.testingsession')),
            ],
            options={
                'ordering': ['rank', '-total_score', 'athlete__username'],
            },
        ),
        migrations.CreateModel(
            name='TestingExerciseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_result', models.CharField(blank=True, help_text='Examples: 24, 7.17 seconds, 5 presses, or white line.', max_length=100)),
                ('numeric_result', models.DecimalField(blank=True, decimal_places=3, help_text='Optional numeric value used later for automatic scoring.', max_digits=10, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('not_completed', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_results', to='performance_testing.athletetestingresult')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_exercise_results', to='performance_testing.testingexercise')),
            ],
            options={
                'ordering': ['exercise__display_order', 'exercise__name'],
                'constraints': [models.UniqueConstraint(fields=('athlete_result', 'exercise'), name='unique_exercise_result_per_athlete_result')],
            },
        ),
        migrations.AddConstraint(
            model_name='athletetestingresult',
            constraint=models.UniqueConstraint(fields=('session', 'athlete'), name='unique_athlete_testing_result_per_session'),
        ),
    ]
