# Generated by Django 6.0.3 on 2026-07-17 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_testing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testingsession',
            name='athletes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'athlete'}, related_name='performance_testing_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testingsession',
            name='allow_athlete_entry',
            field=models.BooleanField(default=False),
        ),
    ]
