# Generated by Django 6.0.3 on 2026-07-17 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_testing', '0002_testingsession_athletes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testingexercise',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_testing_exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testingexercise',
            name='higher_is_better',
            field=models.BooleanField(default=True, help_text='Select this when a higher result is better. Turn it off when a lower time or score is better.'),
        ),
    ]
