# Generated by Django 6.0.3 on 2026-07-27 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_testing', '0003_testingexercise_created_by_and_more'),
        ('practice_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingsession',
            name='practice_plan',
            field=models.ForeignKey(blank=True, help_text='Optional practice plan where this testing session will be completed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testing_sessions', to='practice_planner.practiceplan'),
        ),
        migrations.AddField(
            model_name='testingsession',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='testingsession',
            name='training_group',
            field=models.ForeignKey(blank=True, help_text='The training group completing this testing session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testing_sessions', to='practice_planner.traininggroup'),
        ),
        migrations.AddField(
            model_name='testingsession',
            name='week_number',
            field=models.PositiveIntegerField(blank=True, help_text='Optional weekly testing number, such as Week 3.', null=True),
        ),
    ]
