# Generated by Django 6.1 on 2026-09-17 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
        ('performance_testing', '0004_testingsession_practice_plan_testingsession_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testingsession',
            name='training_group',
            field=models.ForeignKey(blank=True, help_text='The training group completing this testing session.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testing_sessions', to='gyms.traininggroup'),
        ),
    ]
