# Generated by Django 6.1 on 2026-09-04 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRoutineSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_date', models.DateField(unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_daily_routine_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-practice_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyRoutineAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('vault', 'Vault'), ('bars', 'Bars'), ('beam', 'Beam'), ('floor', 'Floor')], max_length=20)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('result', models.CharField(choices=[('hit', 'Hit'), ('mid', 'Mid'), ('missed', 'Missed')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(limit_choices_to={'role': 'athlete'}, on_delete=django.db.models.deletion.CASCADE, related_name='daily_routine_attempts', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_routine_attempts', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='routine_tracker.dailyroutinesession')),
            ],
            options={
                'ordering': ['athlete__first_name', 'athlete__last_name', 'event', 'attempt_number'],
                'indexes': [models.Index(fields=['athlete', 'event', 'created_at'], name='routine_tra_athlete_2240b3_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'athlete', 'event', 'attempt_number'), name='unique_daily_routine_attempt')],
            },
        ),
    ]
